import problem1 from "./src/problem1.js";
// import problem2 from "./src/problem2.js";
// import problem3 from "./src/problem3.js";
// import problem4 from "./src/problem4.js";
// import problem5 from "./src/problem5.js";
// import problem6 from "./src/problem6.js";
// import problem7 from "./src/problem7.js";
// import problem8 from "./src/problem8.js";
// import problem10 from "./src/problem10.js";
// import problem11 from "./src/problem11.js";
// import problem12 from "./src/problem12.js";
// import problem13 from "./src/problem13.js";
// import problem14 from "./src/problem14.js";
// import problem15 from "./src/problem15.js";
// import problem16 from "./src/problem16.js";
// import problem17 from "./src/problem17.js";
// import problem18 from "./src/problem18";

// problem1();
// problem2();
// problem3();
// problem4();
// problem5();
// problem6();
// problem7();
// problem8();
// problem10();
// problem11();
// problem12();
// problem13("Ahmad");
// problem14();
// problem15();
// problem16();
// problem17();
// problem18();
